# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:

  compile_vert_shaders:
    # desc: Compile vertex shaders
    sources: ['shaders/source/*.vert.hlsl']
    generates: ['shaders/compiled/*.spv']
    cmds:
      - for: sources
        cmd: "{{.VULKAN_SDK}}/bin/glslc -fshader-stage=vertex -o shaders/compiled/{{trimSuffix \".hlsl\" (base .ITEM)}}.spv {{.ITEM}}"

  compile_frag_shaders:
    # desc: Compile vertex shaders
    sources: ['shaders/source/*.frag.hlsl']
    generates: ['shaders/compiled/*.spv']
    cmds:
      - for: sources
        cmd: "{{.VULKAN_SDK}}/bin/glslc -fshader-stage=fragment -o shaders/compiled/{{trimSuffix \".hlsl\" (base .ITEM)}}.spv {{.ITEM}}"

